version: '3'
services:
  db:
    image: "postgres"
    env_file:
      - db.env
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data
volumes:
  database-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: C:\database\ebank\data